### ISSUE TITLE
Fails when discovering devices

### ISSUE THREAD

**Issue by sognen** [techno-tim/techno-broadlink#5]
Hi,
I'm getting an error message when discovering devices. See under log. "Discovered 0 devices" is displayed on the screen.
All my devices are found when using Broadlink Manager https://github.com/t0mer/broadlinkmanager-docker.

Devices:
RM2
RM3/mini
A1

I using the docker image.

Best Regards,
Cato

RM2
# broadlink_cli --type 0x2712 --host 192.168.1.205 --mac XXXXXXXXXX
Device file data (to be used with --device @filename in broadlink_cli) : 
sensors = {'temperature': 26.6}
broadcast ip is: 192.168.1.255
args: Namespace(dst_ip='192.168.1.255', ip='192.168.1.104', timeout=2)
Discovering...
devices [<rm: Broadlink RM pro/pro+ (0x2712) at 192.168.1.205:80 | b4:43:0d:38:fb:9c | 智能遥控 | Unlocked>, <a1: Broadlink e-Sensor (0x2714) at 192.168.1.239:80 | b4:43:0d:70:21:8e | 空气质量仪 | Unlocked>]
found [<rm: Broadlink RM pro/pro+ (0x2712) at 192.168.1.205:80 | b4:43:0d:38:fb:9c | 智能遥控 | Unlocked>, <a1: Broadlink e-Sensor (0x2714) at 192.168.1.239:80 | b4:43:0d:70:21:8e | 空气质量仪 | Unlocked>]
###########################################
RM2
# broadlink_cli --type 0x2712 --host 192.168.1.205 --mac XXXXXXXXXX
Device file data (to be used with --device @filename in broadlink_cli) : 
sensors = {'temperature': 26.6}
broadcast ip is: 192.168.1.255
args: Namespace(dst_ip='192.168.1.255', ip='192.168.1.104', timeout=2)
Discovering...
ERROR:api:Exception on /discover [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./api.py", line 60, in discover
    return jsonify(discover_devices(host_ip))
  File "/app/broadlink_service.py", line 85, in discover_devices
    humidity = sensors['humidity']
KeyError: 'humidity'

**Comment by sognen** [comment]
I commented out the line humidity = sensors['humidity'] and it now discovers my RM devices.

**Comment by timothystewart6** [comment]
Thank you!  I will fix this soon!

**Comment by timothystewart6** [comment]
this was closed by https://github.com/techno-tim/techno-broadlink/commit/bb1b4f1ba9b82c59723cec7037ab476a750357db

**Comment by timothystewart6** [comment]
@sognen  Let me know if you've had a chance to try the new version!

**Comment by sognen** [comment]
Hi,
Unfortunately the error is back.  After removing line 86 it works again.

Traceback (most recent call last):


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./api.py", line 60, in discover
    return jsonify(discover_devices(host_ip))
  File "/app/broadlink_service.py", line 86, in discover_devices
    humidity = sensors['humidity']
KeyError: 'humidity'
